
# See http://about.travis-ci.org/docs/user/build-configuration/
dist: bionic

language: scala
services: mongodb

scala:
  - 2.12.12
  - 2.13.3

branches:
  only:
    - master
notifications:
  email:
    recipients:
      - tom@sfxcode.com
jdk:
  - openjdk11
  - openjdk8

before_script:
  - echo "replSet = myReplSetName" | sudo tee -a /etc/mongodb.conf
  - sudo systemctl unmask mongod && sudo service mongod start
  - sleep 20
  - mongo --eval 'rs.initiate()'
  - sleep 15

after_success:
  - bash <(curl -s https://codecov.io/bash)

