
# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
services: mongodb

scala:
   - 2.11.11
   - 2.12.6
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - tom@sfxcode.com
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer