name: Github Release and Changelog

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  update-change-infos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@main
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Create Release
        uses: ncipollo/release-action@main
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}

      - name: Update versions file
        run: |
          echo "{\"mongocamp\": \"${{ github.ref_name }}\"}" > ./docs/versions.json;
          git add ./docs/versions.json

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@main
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }}'
          file_pattern: CHANGELOG.md

      - name: Set up JDK
        uses: coursier/setup-action@main
        with:
          jvm: graalvm-java17:22.3.3
          apps: sbt scala scalac

      - name: Install pnpm
        uses: pnpm/action-setup@main
        with:
          version: 6.0.2

      - name: Build and deploy Docu
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "ci@mongocamp.dev"
          git config --global user.name "MongoCamp CI"
          sh ./deploy_ghpages.sh